var publicQ = [{
    "type": "Q",
    "text": "喜歡並且會看成人內容",
    "point": "5"
}, {
    "type": "Q",
    "text": "拍過暴露/性愛照片",
    "point": "10"
}, {
    "type": "Q",
    "text": "曾經有為了刺激而不穿內衣出門",
    "point": "15"
}, {
    "type": "Q",
    "text": "購置過成人玩具給自己用",
    "point": "20"
}, {
    "type": "Q",
    "text": "主動勾引過同性/異性",
    "point": "10"
}, {
    "type": "Q",
    "text": "勾引過有伴侶的同性/異性",
    "point": "20"
}, {
    "type": "Q",
    "text": "喜歡和陌生人發生肌膚接觸",
    "point": "15"
}, {
    "type": "Q",
    "text": "喜歡著裝暴露/裸體時感受到他人的視線",
    "point": "10"
}, {
    "type": "Q",
    "text": "能夠接受和陌生人發生性關係",
    "point": "20"
}, {
    "type": "Q",
    "text": "在公共場所盯過陌生人的下體",
    "point": "15"
}, {
    "type": "Q",
    "text": "喜歡撫摸同性/異性的私處",
    "point": "20"
}, {
    "type": "Q",
    "text": "幻想過被強姦/輪姦等非普通的色情場警",
    "point": "20"
}, {
    "type": "L",
    "text": "幻想過發生過關係的對象有......(多選)",
    "point": ""
}, {
    "type": "LQ",
    "text": "．好友/網友",
    "point": "15"
}, {
    "type": "LQ",
    "text": "．親人/親戚/閨蜜的另一半/陌生人",
    "point": "20"
}, {
    "type": "Q",
    "text": "會對他人的衣物/氣味/用過的物件而逞生興奮感",
    "point": "15"
}, {
    "type": "Q",
    "text": "你是BDSM圈子的人",
    "point": "20"
}, {
    "type": "T",
    "text": "平日指數",
    "point": ""
}]

var privateQ = [{
    "type": "L",
    "text": "每週平均自慰......",
    "point": ""
}, {
    "type": "LQ",
    "text": "．2次",
    "point": "5"
}, {
    "type": "LQ",
    "text": "．3次",
    "point": "10"
}, {
    "type": "LQ",
    "text": "．4次或以上",
    "point": "20"
}, {
    "type": "Q",
    "text": "有約炮經驗",
    "point": "10"
}, {
    "type": "L",
    "text": "在......自願破處",
    "point": ""
}, {
    "type": "LQ",
    "text": "．18歲",
    "point": "5"
}, {
    "type": "LQ",
    "text": "．17歲",
    "point": "10"
}, {
    "type": "LQ",
    "text": "．16歲",
    "point": "15"
}, {
    "type": "LQ",
    "text": "．15歲或之前",
    "point": "20"
}, {
    "type": "Q",
    "text": "超過2個洞或以上都被開發過",
    "point": "15"
}, {
    "type": "L",
    "text": "有過......的性愛/調教經驗",
    "point": ""
}, {
    "type": "LQ",
    "text": "．2個人",
    "point": "5"
}, {
    "type": "LQ",
    "text": "．3個人",
    "point": "10"
}, {
    "type": "LQ",
    "text": "．4個人或以上",
    "point": "20"
}, {
    "type": "Q",
    "text": "有過多P的經驗",
    "point": "15"
}, {
    "type": "Q",
    "text": "喜歡喝下他人或自己的液體",
    "point": "10"
}, {
    "type": "Q",
    "text": "喜歡揪或者被揪頭髮掐脖子",
    "point": "10"
}, {
    "type": "Q",
    "text": "喜歡給予或者接受言語上的辱罵羞辱",
    "point": "20"
}, {
    "type": "Q",
    "text": "喜歡言語上主動羞辱自己(如：我是你的母狗/公狗)",
    "point": "15"
}, {
    "type": "Q",
    "text": "享受被叫或者是叫\"主人\"等羞恥稱呼",
    "point": "15"
}, {
    "type": "Q",
    "text": "願意給/看現實中沒有見過面的網友呻吟，羞恥的照片/視頻",
    "point": "20"
}, {
    "type": "Q",
    "text": "看完/填完這個紫評表後，身體有了感覺",
    "point": "20"
}, {
    "type": "T",
    "text": "私下里指數",
    "point": ""
}]
